### ISSUE TITLE
Required credits in other projects 

### ISSUE THREAD

**Issue by JustTemmie** [Pr0chy/jellyfin-rpc-discord-bridge#1]
shitty issue name aside, i'm the creator of [steam presence](https://github.com/JustTemmie/steam-presence), an app similar to jellyfin-rpc, but for steam games and I'd like to create a discord bridge for that project, basing it on this one.

steam presence uses the same MIT license as this project, you alright if i just dump something along the lines of this to the bottom of the readme file?
`Credit to "Dominik Procházka" / "Pr0chy" for co-authoring the discord bridge`

**Comment by prochy-exe** [comment]
yeah of course!
